### PR TITLE
Feature/importe log feature

### PR DESCRIPTION
**Pull request by Renardjojo**
Log example : 

================================
| LOG Green Portal Engine
| Date : 25-1-2021 14:38:43
================================

GPEngine: 14:38:43 logInitializationStart being initialized...
GPEngine: 14:38:43 logInitializationStep initialization [50%]
GPEngine: 14:38:43 log
GPEngine: 14:38:43 HELP: logHelp
GPEngine: 14:38:43 WARNING: logWarning
GPEngine: 14:38:43 ERROR: logError
GPEngine: 14:38:43 logInitializationEnd initialization completed
GPEngine: 14:38:43 ERROR: C:\Users\utilisateur\Desktop\GPEngine\GP_Engine\src\main.cpp:24: function "main()" : functError
GPEngine: 14:38:43 WARNING: C:\Users\utilisateur\Desktop\GPEngine\GP_Engine\src\main.cpp:25: function "main()" :functWarning
GPEngine: 14:38:43 ERROR: [31mAssertion[0m in function main C:\Users\utilisateur\Desktop\GPEngine\GP_Engine\src\main.cpp:27
Expression "[1mfalse[0m" == false.

### CODE REVIEW

**Review by Korotsu — APPROVED** [review]
Really nice looking work !

**Comment by Renardjojo** [comment]
Consol example : 
image

**Comment by Bad-Sam** [comment]
Here are a few feedbacks:
- The text-formatting macro would be clearer with their full uncompressed name, i.e. `UNDL(x)` --> `UNDERLINED(x)`, or `BWHT(x)` --> `BWHITE(x)`. Same for `ELogSetting`'s values

- If that's ok to you, I would replace __FUNCTION__ with __FUNCSIG__ where possible. __FUNCSIG__ gives more context, and is somewhat prettier :
image

- At [Log.inl:256](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/src/Log.inl#L254), I would replace the `assert(false)` with a log warning/error message to give a clearer feedback to the developer. This will not create a crash, nor will it make the logs misbehave.

- Fix some typos here and there (alway --> always), and shorten some names (printLogFileIfWarningHappend --> printLogFileOnWarning). We can change it together in class.

- Group all the `bool` at [Log.hpp:87](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/include/Engine/Core/Debug/Log.hpp#L87) into a single `uint8_t`, set the `ELogSetting`'s values to shifted bits (1, 2, 4, etc.), and associate each bits of the `uint8_t` to a value of the enum. Sample code:
```C++
enum ELogSetting
{
    DISPLAY_DATE         = (1u << 1),
    DISPLAY_HOUR         = (1u << 2),
    DISPLAY_WITH_COLOR   = (1u << 3),
    ALWAY_PRINT_LOG_FILE = (1u << 4),
    PRINT_LOG_FILE_WRNG  = (1u << 5),
    PRINT_LOG_FILE_ERR   = (1u << 6)
};

class Log
{
    protected:
        static uint8_t flags;
};

int main()
{
  Log logs;
  // Option 1
  logs.flags |= DISPLAY_WITH_COLOR;
  // Option 2
  logs.setFlag(ELogSetting::DISPLAY_WITH_COLOR);
}
```

- (Optional) Keep count of warnings/errors/notes

I have more feedbacks, but I need to have dinner now. See you in a few minutes

**Review by badsami — CHANGES_REQUESTED** [review]
Here are a few feedbacks:
- Assertion should always have a message to explain what is wrong to the developper. In [Assert.hpp](https://github.com/GP-Engine-team/GP_Engine/blob/feature/ImporteLogFeature/include/Engine/Core/Debug/Assert.hpp), I would only define the `GPE_assert(condition, message)` macro, so a message is made mandatory.

- The text-formatting macro would be clearer with their full uncompressed name, i.e. `UNDL(x)` --> `UNDERLINED(x)`, or `BWHT(x)` --> `BWHITE(x)`. Same for `ELogSetting`'s values

- If that's ok to you, I would replace `__FUNCTION__` with `__FUNCSIG__` where possible. `__FUNCSIG__` gives more context, and is somewhat prettier:
image

- At [Log.inl:256](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/src/Log.inl#L254), I would replace the `assert(false)` with a log warning/error message to give a clearer feedback to the developer. This will not create a crash, nor will it make the logs misbehave.

- Fix some typos here and there (alway --> always), and shorten some names (printLogFileIfWarningHappend --> printLogFileOnWarning). We can change it together in class.

- Group all the `bool` at [Log.hpp:87](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/include/Engine/Core/Debug/Log.hpp#L87) into a single `uint8_t`, set the `ELogSetting`'s values to shifted bits (1, 2, 4, etc.), and associate each bits of the `uint8_t` to a value of the enum. Sample code:
```C++
class Log
{
    public:
        enum ESetting
        {
            DISPLAY_DATE         = (1u << 1),
            DISPLAY_HOUR         = (1u << 2),
            DISPLAY_WITH_COLOR   = (1u << 3),
            ALWAY_PRINT_LOG_FILE = (1u << 4),
            PRINT_LOG_FILE_WRNG  = (1u << 5),
            PRINT_LOG_FILE_ERR   = (1u << 6)
        };

    private:
        static uint8_t settings;

    public:
        void setSetting(Log::ESetting flag)
        { settings |= flag; }

       void removeSetting(Log::ESetting flag)
       { settings &= ~flag; }
};

int main()
{
    Log logs;

    logs.setSetting(Log::ESetting::DISPLAY_WITH_COLOR);

    return 0;
}
```
Flags will take less memory, and the `Log::setSetting()` and `Log::getSetting()` can be made shorter and faster with this change, though this change imply adding some method to `Log`

- Use the [stderr](https://en.cppreference.com/w/c/io) or the [std::cerr](https://en.cppreference.com/w/cpp/io/cerr) output stream, which are specialized for diagnostic/error outputting. They both are thread-safe and flush their content by default

- Since `Log` is meant to be used internally to raise warnings, errors and notes, we don't need to make its destructor virtual. I think we can remove the `virtual` at [Log.hpp:114](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/include/Engine/Core/Debug/Log.hpp#L114).

- [`Log::init()`](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/src/Log.inl#L3) in [Log.inl](https://github.com/GP-Engine-team/GP_Engine/blob/feature/ImporteLogFeature/src/Log.inl) is not declared `inline`

- The [`Log::init()`](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/src/Log.inl#L3) and [`Log::release()`](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/src/Log.inl#L9) methods should be put in `Log`'s constructor and destructor, respectively. This will prevent possible misuses of Log (such as forgetting to close the opened `std::ofstream`).
This implies either:
(a) checking whether the logs are already initialized, and call or don't call logHeading() as a consequence;
(b) removing the log header
(c) making `Log` non-static, so more than one log configuration and output file can be defined

- As is, compilation under Visual Studio 2019 returns 2 errors :
image
Adding `$(SolutionDir)/include` to the Include Directories property in the solution's properties solves the problem:
image

- Don't forget to put `Log.inl` and `Log.cpp` in `src/Engine/Code/Debug/`

- (Optional) Keep count of warnings/errors/notes

- (Optional) In [Assert.hpp](https://github.com/GP-Engine-team/GP_Engine/blob/feature/ImporteLogFeature/include/Engine/Core/Debug/Assert.hpp) and [Log.hpp:55](https://github.com/GP-Engine-team/GP_Engine/blob/9d081d524aedb3c091fc32823579514d4579fc80/include/Engine/Core/Debug/Log.hpp#L55), I would use `fprintf()` to prevent the potential instantiation of 2 `std::string` at every call of `GPE_assert()`, `functError()` or `functWarning()`

- (Optional) Update non-conforming code which does not abide by the code normes (non capital SNAKE_CASE macros, extraneous spaces between function names and parameters, missing spaces after `if`, etc.). But we may as well wait for the .clang-format merge, so that's up to you!

**Comment by Renardjojo** [comment]
"The text-formatting macro would be clearer with their full uncompressed name, i.e. UNDL(x) --> UNDERLINED(x), or BWHT(x) --> BWHITE(x). Same for ELogSetting's values"
I think that it may be too verbose, i.e. : BACKGROUND_WHIT([...])
A good deal could be replace BWHT by B_WHITE

**Comment by Renardjojo** [comment]
- The name init and release were not exactly. Release print file and init just create file header. Log work without init and is not singleton
- I am waiting for an answer about the macro typo and don't change it for now.
- Count of warnings/errors/notes will be made if we create a feature to display it in the editor (avoid perform counter without using it)
- Source file and in stay in src folder for now (To discuss)
- LogError and LogWarning were not recreated with format arg to avoid function duplication of code. Use stringFormat to do it.
- StringFormat function is in folders tools ?? Ok ?

**Comment by badsami** [comment]
> 
> 
> "The text-formatting macro would be clearer with their full uncompressed name, i.e. UNDL(x) --> UNDERLINED(x), or BWHT(x) --> BWHITE(x). Same for ELogSetting's values"
> I think that it may be too verbose, i.e. : BACKGROUND_WHIT([...])
> A good deal could be replace BWHT by B_WHITE

That is fine by me. I will approve the merge request as soon as you're done with your changes.
Nice work!

**Review by badsami — APPROVED** [review]

**Pull request merged**
