### PR TITLE
Feature/test3 william

### PR DESCRIPTION
**Pull request by Korotsu**
Steps to make the Clang-format work :
1- Create a new element called .clang-format to the upside or beside the sources files 
you want them to be formatted by the .clang-format file;

2- Customize your .Clang-format with the rule you want;

3- In your Cpp find the shortcut you have to format the document ( Default: Ctrl+K -> Ctrl+D );

4- Enjoy your nice formatted code!

Steps to make the project working :

1- Clone the Features/Test3_William branch;

2- Open the GP_Engine.sln;

3- try the formatting shortcut ( Default : Ctrl+K -> Ctrl+D );

4- Enjoy!

### CODE REVIEW

**Comment by Renardjojo** [comment]
I have already create the project in pull request #7. Please remove the commit of the project and just add the .clang-format without the main

**Review by Renardjojo — CHANGES_REQUESTED** [review]
I have already create the project in pull request #7. Please remove the commit of the project and just add the .clang-format without the main

**Review by Renardjojo — CHANGES_REQUESTED** [review]
I have already create the project in pull request #7. Please remove the commit of the project and just add the .clang-format without the main

**Review by Korotsu — COMMENTED** [review]
Make the changes that Jonathan asked for.

**Review by Renardjojo — APPROVED** [review]
Nice

**Review by badsami — APPROVED** [review]

**Pull request merged**
